module.exports = {
  purge: ['./{apps,libs}/*/src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'button-primary': 'var(--color-button-primary)',
        'button-primary-hover': 'var(--color-button-primary-hover)',
        'button-text-primary': 'var(--color-button-text-primary)',
        'button-text-primary-hover': 'var(--color-button-text-primary-hover)',
        'button-secondary': 'var(--color-button-secondary)',
        'button-secondary-hover': 'var(--color-button-secondary-hover)',
        'button-text-secondary': 'var(--color-button-text-secondary)',
        'button-text-secondary-hover':
          'var(--color-button-text-secondary-hover)',
        'button-default': 'var(--color-button-default)',
        'button-default-hover': 'var(--color-button-default-hover)',
        'button-text-default': 'var(--color-button-text-default)',
        'button-text-default-hover': 'var(--color-button-text-default-hover)',
        'border-primary': 'var(--color-border-primary)',
        'border-primary-hover': 'var(--color-border-primary-hover)',
        'border-secondary': 'var(--color-border-secondary)',
        'border-secondary-hover': 'var(--color-border-secondary-hover)',
        'border-default': 'var(--color-border-default)',
        'border-default-hover': 'var(--color-border-default-hover)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-link': 'var(--color-text-link)',
        'text-link-hover': 'var(--color-text-link-hover)',
        'background-default': 'var(--color-background-default)',
      },
    },
  },
  variants: {},
  plugins: [],
}
