export const someSourcesFixture = () => [
  {
    type: 'harvester',
    logo: null,
    filter: null,
    uiConfig: null,
    serviceRecord: null,
    creationDate: {},
    groupOwner: null,
    uuid: '77992c40-5ba9-41a8-80e7-510576221cbc',
    name: 'Agence ORE',
    label: {
      dut: 'Agence ORE',
      spa: 'Agence ORE',
      chi: 'Agence ORE',
      fin: 'Agence ORE',
      pol: 'Agence ORE',
      nor: 'Agence ORE',
      tur: 'Agence ORE',
      rus: 'Agence ORE',
      ara: 'Agence ORE',
      por: 'Agence ORE',
      vie: 'Agence ORE',
      ger: 'Agence ORE',
      cat: 'Agence ORE',
      ita: 'Agence ORE',
      slo: 'Agence ORE',
      fre: 'Agence ORE',
      eng: 'Agence ORE',
    },
  },
  {
    type: 'portal',
    logo: null,
    filter: null,
    uiConfig: null,
    serviceRecord: null,
    creationDate: null,
    groupOwner: null,
    uuid: '972b12aa-08dc-4d29-8a10-ff44ecef1dda',
    name: 'Géo2France',
    label: {
      dut: 'Géo2France',
      spa: 'Géo2France',
      chi: 'Géo2France',
      fin: 'Géo2France',
      pol: 'Géo2France',
      nor: 'Géo2France',
      tur: 'Géo2France',
      rus: 'Géo2France',
      ara: 'Géo2France',
      por: 'Géo2France',
      vie: 'Géo2France',
      ger: 'Géo2France',
      cat: 'Géo2France',
      ita: 'Géo2France',
      slo: 'Géo2France',
      fre: 'Géo2France',
      eng: 'Géo2France',
    },
  },
  {
    type: 'harvester',
    logo: null,
    filter: null,
    uiConfig: null,
    serviceRecord: null,
    creationDate: {},
    groupOwner: null,
    uuid: '88d1dad6-ef31-4af8-9adb-031daa0b0965',
    name: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
    label: {
      dut: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      spa: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      chi: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      fin: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      pol: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      nor: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      tur: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      rus: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      ara: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      por: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      vie: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      ger: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      cat: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      ita: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      slo: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      fre: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
      eng: 'Métropole Européenne de Lille (ODS DCAT TO ISO)',
    },
  },
]
