/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AnalysisStatusEnumApiModel =
  | 'PENDING'
  | 'ANALYZING'
  | 'DONE'
  | 'ERROR'

export const AnalysisStatusEnumApiModel = {
  PENDING: 'PENDING' as AnalysisStatusEnumApiModel,
  ANALYZING: 'ANALYZING' as AnalysisStatusEnumApiModel,
  DONE: 'DONE' as AnalysisStatusEnumApiModel,
  ERROR: 'ERROR' as AnalysisStatusEnumApiModel,
}
