/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CRSApiModel } from './cRS.api.model'

export interface DatasetPublishRequestApiModel {
  nativeName?: string
  publishedName?: string
  title?: string
  _abstract?: string
  encoding?: string
  tags?: Array<string>
  crs?: CRSApiModel
  /**
   * Dataset creation date, in RFC3339 format
   */
  creationDate?: string
  /**
   * Optional, scale the data was created for (e.g. 500000 for a 1:500000 scale)
   */
  scale?: number
  creationProcessDescription?: string
}
