/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatasetPublishingStatusApiModel } from './datasetPublishingStatus.api.model'

/**
 * Describes the processing status of a publishing job for a given upload
 */
export interface PublishJobStatusApiModel {
  /**
   * Identifier for the upload processing job
   */
  jobId?: string
  /**
   * Estimated completion progress, from 0 to 1.
   */
  progress?: number
  status?: PublishJobStatusApiModel.StatusEnum
  /**
   * short description of the error that prevents the job to complete successfully
   */
  error?: string
  datasets?: Array<DatasetPublishingStatusApiModel>
}
export namespace PublishJobStatusApiModel {
  export type StatusEnum = 'PENDING' | 'RUNNING' | 'DONE' | 'ERROR'
  export const StatusEnum = {
    PENDING: 'PENDING' as StatusEnum,
    RUNNING: 'RUNNING' as StatusEnum,
    DONE: 'DONE' as StatusEnum,
    ERROR: 'ERROR' as StatusEnum,
  }
}
