/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PublishStatusEnumApiModel = 'PENDING' | 'RUNNING' | 'DONE' | 'ERROR'

export const PublishStatusEnumApiModel = {
  PENDING: 'PENDING' as PublishStatusEnumApiModel,
  RUNNING: 'RUNNING' as PublishStatusEnumApiModel,
  DONE: 'DONE' as PublishStatusEnumApiModel,
  ERROR: 'ERROR' as PublishStatusEnumApiModel,
}
