/**
 * GeoNetwork 4.0.0 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamespaceApiModel } from './namespace.api.model'
import { DocumentApiModel } from './document.api.model'
import { ParentApiModel } from './parent.api.model'

export interface ElementApiModel {
  parent?: ParentApiModel
  name?: string
  namespace?: NamespaceApiModel
  additionalNamespaces?: Array<object>
  attributes?: Array<object>
  content?: Array<object>
  text?: string
  attribute?: ElementApiModel
  rootElement?: boolean
  contentSize?: number
  qualifiedName?: string
  namespaceURI?: string
  namespacePrefix?: string
  textTrim?: string
  children?: Array<object>
  textNormalize?: string
  descendants?: object
  value?: string
  document?: DocumentApiModel
  parentElement?: ElementApiModel
}
