[global]
geonetwork4_api_url = "https://geonetwork-ui.labs.camptocamp.com/geonetwork/srv/api"

[theme]
primary_color = "#c82850"
secondary_color = "#001638"
main_color = "#555"
background_color = "#fdfbff"
header_background = "#001638"

[search]

[metadata-quality]

[map]
