/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublishStepEnumApiModel } from './publishStepEnum.api.model'
import { PublishStatusEnumApiModel } from './publishStatusEnum.api.model'

/**
 * Describes the status of publishing a given dataset
 */
export interface DatasetPublishingStatusApiModel {
  /**
   * Name of the dataset in the uploaded package, necessary to identify which dataset to publish from the UploadJobStatus
   */
  nativeName?: string
  /**
   * Name of the GeoServer workspace under which the dataset has been published.
   */
  publishedWorkspace?: string
  /**
   * Final name under which the layer was published to GeoServer. It may have been modified from the requested layer name in order to avoid duplication if a layer with such name already exists in the target GeoServer workspace.
   */
  publishedName?: string
  /**
   * Identifier for the metadta record created while publishing the dataset\'s metadata to GeoNetwork.
   */
  metadataRecordId?: string
  title?: string
  status?: PublishStatusEnumApiModel
  /**
   * short description of the error that prevents the dataset to be published
   */
  error?: string
  /**
   * true if this dataset is scheduled to be published (as requested through a PublishRequest)
   */
  publish?: boolean
  /**
   * Estimated completion progress, from 0 to 1.
   */
  progress?: number
  progressStep?: PublishStepEnumApiModel
}
