/**
 * DataFeeder API
 * This API covers dataset upload and publishing features of the application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: psc@georchestra.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PublishStepEnumApiModel =
  | 'SKIPPED'
  | 'SCHEDULED'
  | 'DATA_IMPORT_STARTED'
  | 'DATA_IMPORT_FINISHED'
  | 'OWS_PUBLISHING_STARTED'
  | 'OWS_PUBLISHING_FINISHED'
  | 'METADATA_PUBLISHING_STARTED'
  | 'METADATA_PUBLISHING_FINISHED'
  | 'OWS_METADATA_UPDATE_STARTED'
  | 'OWS_METADATA_UPDATE_FINISHED'
  | 'COMPLETED'

export const PublishStepEnumApiModel = {
  Skipped: 'SKIPPED' as PublishStepEnumApiModel,
  Scheduled: 'SCHEDULED' as PublishStepEnumApiModel,
  DataImportStarted: 'DATA_IMPORT_STARTED' as PublishStepEnumApiModel,
  DataImportFinished: 'DATA_IMPORT_FINISHED' as PublishStepEnumApiModel,
  OwsPublishingStarted: 'OWS_PUBLISHING_STARTED' as PublishStepEnumApiModel,
  OwsPublishingFinished: 'OWS_PUBLISHING_FINISHED' as PublishStepEnumApiModel,
  MetadataPublishingStarted:
    'METADATA_PUBLISHING_STARTED' as PublishStepEnumApiModel,
  MetadataPublishingFinished:
    'METADATA_PUBLISHING_FINISHED' as PublishStepEnumApiModel,
  OwsMetadataUpdateStarted:
    'OWS_METADATA_UPDATE_STARTED' as PublishStepEnumApiModel,
  OwsMetadataUpdateFinished:
    'OWS_METADATA_UPDATE_FINISHED' as PublishStepEnumApiModel,
  Completed: 'COMPLETED' as PublishStepEnumApiModel,
}
