/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetadataCategoryApiModel } from './metadataCategory.api.model'

/**
 * Group details
 */
export interface GroupApiModel {
  logo?: string
  website?: string
  defaultCategory?: MetadataCategoryApiModel
  allowedCategories?: Array<MetadataCategoryApiModel>
  enableAllowedCategories?: boolean
  reserved?: boolean
  email?: string
  referrer?: number
  description?: string
  id?: number
  name?: string
  label?: { [key: string]: string }
}
