/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GroupPrivilegeApiModel {
  operations?: { [key: string]: boolean }
  group?: number
  userProfiles?: Array<GroupPrivilegeApiModel.UserProfilesEnum>
  userGroup?: boolean
  reserved?: boolean
  userProfile?: Array<GroupPrivilegeApiModel.UserProfileEnum>
}
export namespace GroupPrivilegeApiModel {
  export const UserProfilesEnum = {
    Administrator: 'Administrator',
    UserAdmin: 'UserAdmin',
    Reviewer: 'Reviewer',
    Editor: 'Editor',
    RegisteredUser: 'RegisteredUser',
    Guest: 'Guest',
    Monitor: 'Monitor',
  } as const
  export type UserProfilesEnum =
    (typeof UserProfilesEnum)[keyof typeof UserProfilesEnum]
  export const UserProfileEnum = {
    Administrator: 'Administrator',
    UserAdmin: 'UserAdmin',
    Reviewer: 'Reviewer',
    Editor: 'Editor',
    RegisteredUser: 'RegisteredUser',
    Guest: 'Guest',
    Monitor: 'Monitor',
  } as const
  export type UserProfileEnum =
    (typeof UserProfileEnum)[keyof typeof UserProfileEnum]
}
