/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.2.7
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ISODateApiModel {
  internalDateTime?: string
  dateAndTime?: string
  dateAsString?: string
  timeInSeconds?: number
  dateOnly?: boolean
  dateYearOnly?: boolean
  dateYearMonthOnly?: boolean
  timeAsString?: string
  seconds?: number
  days?: number
  years?: number
  months?: number
  hours?: number
  minutes?: number
  dateAndTimeUtc?: string
}
