/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfoReportApiModel } from './infoReport.api.model'
import { ReportApiModel } from './report.api.model'

export interface MetadataProcessingReportApiModel {
  errors?: Array<ReportApiModel>
  infos?: Array<InfoReportApiModel>
  uuid?: string
  totalRecords?: number
  metadata?: Set<number>
  metadataErrors?: { [key: string]: Array<ReportApiModel> }
  metadataInfos?: { [key: string]: Array<InfoReportApiModel> }
  numberOfRecordNotFound?: number
  numberOfRecordsNotEditable?: number
  numberOfNullRecords?: number
  numberOfRecordsProcessed?: number
  numberOfRecordsUnchanged?: number
  numberOfRecordsWithErrors?: number
  numberOfRecords?: number
  startIsoDateTime?: string
  endIsoDateTime?: string
  ellapsedTimeInSeconds?: number
  totalTimeInSeconds?: number
  running?: boolean
  type?: string
}
