/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MetadataResourceExternalManagementPropertiesApiModel {
  id?: string
  url?: string
  validationStatus?: MetadataResourceExternalManagementPropertiesApiModel.ValidationStatusEnum
}
export namespace MetadataResourceExternalManagementPropertiesApiModel {
  export const ValidationStatusEnum = {
    Unknown: 'UNKNOWN',
    Valid: 'VALID',
    Incomplete: 'INCOMPLETE',
  } as const
  export type ValidationStatusEnum =
    (typeof ValidationStatusEnum)[keyof typeof ValidationStatusEnum]
}
