/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OperationApiModel {
  reserved?: boolean
  reservedOperation?: OperationApiModel.ReservedOperationEnum
  id?: number
  name?: string
  label?: { [key: string]: string }
}
export namespace OperationApiModel {
  export const ReservedOperationEnum = {
    View: 'view',
    Download: 'download',
    Editing: 'editing',
    Notify: 'notify',
    Dynamic: 'dynamic',
    Featured: 'featured',
  } as const
  export type ReservedOperationEnum =
    (typeof ReservedOperationEnum)[keyof typeof ReservedOperationEnum]
}
