/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.2.7
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FcatApiModel } from './fcat.api.model.js'
import { SourceApiModel } from './source.api.model.js'
import { RelatedApiModel } from './related.api.model.js'
import { HasfeaturecatsApiModel } from './hasfeaturecats.api.model.js'
import { HassourceApiModel } from './hassource.api.model.js'
import { ParentApiModel } from './parent.api.model.js'
import { ThumbnailApiModel } from './thumbnail.api.model.js'
import { SiblingsApiModel } from './siblings.api.model.js'
import { OnlineApiModel } from './online.api.model.js'
import { ServiceApiModel } from './service.api.model.js'
import { AssociatedApiModel } from './associated.api.model.js'
import { DatasetApiModel } from './dataset.api.model.js'
import { ChildrenApiModel } from './children.api.model.js'

export interface RelatedResponseApiModel {
  children?: ChildrenApiModel
  parent?: ParentApiModel
  siblings?: SiblingsApiModel
  associated?: AssociatedApiModel
  services?: ServiceApiModel
  datasets?: DatasetApiModel
  fcats?: FcatApiModel
  hasfeaturecats?: HasfeaturecatsApiModel
  sources?: SourceApiModel
  hassources?: HassourceApiModel
  related?: RelatedApiModel
  onlines?: OnlineApiModel
  thumbnails?: ThumbnailApiModel
}
