/**
 * GeoNetwork 4.0.3 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.3
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DescriptionApiModel } from './description.api.model'
import { MultilingualValueApiModel } from './multilingualValue.api.model'

export interface RelatedMetadataItemApiModel {
  id?: string
  url?: MultilingualValueApiModel
  type?: string
  title: MultilingualValueApiModel
  description: DescriptionApiModel
  mdType: Array<string>
  origin?: string
}
