/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RelatedSiblingMetadataItemApiModel } from './relatedSiblingMetadataItem.api.model'

export interface SiblingsApiModel {
  item?: Array<RelatedSiblingMetadataItemApiModel>
}
