/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface StatusValueApiModel {
  type?: StatusValueApiModel.TypeEnum
  notificationLevel?: StatusValueApiModel.NotificationLevelEnum
  displayOrder?: number
  reserved_JpaWorkaround?: string
  reserved?: boolean
  id?: number
  name?: string
  label?: { [key: string]: string }
}
export namespace StatusValueApiModel {
  export const TypeEnum = {
    Workflow: 'workflow',
    Task: 'task',
    Event: 'event',
  } as const
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum]
  export const NotificationLevelEnum = {
    StatusUserOwner: 'statusUserOwner',
    CatalogueAdministrator: 'catalogueAdministrator',
    CatalogueProfileAdministrator: 'catalogueProfileAdministrator',
    CatalogueProfileUserAdmin: 'catalogueProfileUserAdmin',
    CatalogueProfileReviewer: 'catalogueProfileReviewer',
    CatalogueProfileEditor: 'catalogueProfileEditor',
    CatalogueProfileRegisteredUser: 'catalogueProfileRegisteredUser',
    CatalogueProfileGuest: 'catalogueProfileGuest',
    RecordProfileReviewer: 'recordProfileReviewer',
    RecordUserAuthor: 'recordUserAuthor',
    RecordGroupEmail: 'recordGroupEmail',
  } as const
  export type NotificationLevelEnum =
    (typeof NotificationLevelEnum)[keyof typeof NotificationLevelEnum]
}
