/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.2.7
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserSecurityApiModel {
  nodeId?: string
  securityNotifications?: Set<UserSecurityApiModel.SecurityNotificationsEnum>
  securityNotificationsString?: UserSecurityApiModel
  authType?: string
}
export namespace UserSecurityApiModel {
  export type SecurityNotificationsEnum = 'UPDATE_HASH_REQUIRED' | 'UNKNOWN'
  export const SecurityNotificationsEnum = {
    UpdateHashRequired: 'UPDATE_HASH_REQUIRED' as SecurityNotificationsEnum,
    Unknown: 'UNKNOWN' as SecurityNotificationsEnum,
  }
}
