/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSecurityApiModel } from './userSecurity.api.model'
import { GrantedAuthorityApiModel } from './grantedAuthority.api.model'
import { AddressApiModel } from './address.api.model'

export interface UserApiModel {
  security?: UserSecurityApiModel
  email?: string
  profile?: UserApiModel.ProfileEnum
  surname?: string
  emailAddresses?: Set<string>
  addresses?: Set<AddressApiModel>
  primaryAddress?: AddressApiModel
  organisation?: string
  kind?: string
  lastLoginDate?: string
  authorities?: Array<GrantedAuthorityApiModel>
  accountNonExpired?: boolean
  accountNonLocked?: boolean
  credentialsNonExpired?: boolean
  enabled?: boolean
  username?: string
  id?: number
  name?: string
}
export namespace UserApiModel {
  export const ProfileEnum = {
    Administrator: 'Administrator',
    UserAdmin: 'UserAdmin',
    Reviewer: 'Reviewer',
    Editor: 'Editor',
    RegisteredUser: 'RegisteredUser',
    Guest: 'Guest',
    Monitor: 'Monitor',
  } as const
  export type ProfileEnum = (typeof ProfileEnum)[keyof typeof ProfileEnum]
}
