/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.2.7
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserFeedbackDTOApiModel {
  uuid?: string
  comment?: string
  rating?: { [key: string]: number }
  ratingAVG?: number
  metadataUUID?: string
  metadataTitle?: string
  authorUserId?: number
  authorName?: string
  authorEmail?: string
  authorOrganization?: string
  approverName?: string
  optionPrivacy?: boolean
  published?: boolean
  parentUuid?: string
  captcha?: string
  date?: string
  showApproveButton?: boolean
  keywords?: Array<string>
}
