/**
 * GeoNetwork 4.2.7 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.2.7
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressApiModel } from './address.api.model'

export interface UserDtoApiModel {
  id?: string
  profile?: string
  username?: string
  name?: string
  surname?: string
  emailAddresses?: Array<string>
  organisation?: string
  addresses?: Array<AddressApiModel>
  kind?: string
  password?: string
  groupsRegisteredUser?: Array<string>
  groupsEditor?: Array<string>
  groupsReviewer?: Array<string>
  groupsUserAdmin?: Array<string>
  enabled?: boolean
  email?: UserDtoApiModel
}
