/**
 * GeoNetwork Data Platform
 * Geonetwork Data Platform REST API definition.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DatavizApiModel {
  /**
   * Configuration ID
   */
  id: number
  /**
   * Metadata uuid
   */
  uuid: string
  /**
   * Configuration of default dataviz for the metadata
   */
  config: object
}
