/**
 * GeoNetwork 4.0.2 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.0.2
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElementApiModel } from './element.api.model'
import { ParentApiModel } from './parent.api.model'
import { DocTypeApiModel } from './docType.api.model'

export interface DocumentApiModel {
  content?: Array<object>
  baseURI?: string
  docType?: DocTypeApiModel
  rootElement?: ElementApiModel
  parent?: ParentApiModel
  document?: DocumentApiModel
  descendants?: object
  contentSize?: number
}
