/**
 * Building Blocks specified in OGC API - Records - Part 1: Core
 * Common components used in the [OGC standard \"OGC API - Records - Part 1: Core\"] (https://docs.ogc.org/DRAFTS/20-004.html).  OGC API - Records - Part 1: Core 1.0 is an OGC Standard. Copyright (c) 2020 Open Geospatial Consortium. To obtain additional rights of use, visit https://www.ogc.org/legal/ .  This document is also available on [OGC](http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/ogcapi-records-1.yaml).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pvretano@pvretano.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The spatial extent of the records in the collection.
 */
export interface ExtentSpatialApiModel {
  /**
   * One or more bounding boxes that describe the spatial extent of the dataset. In the Core only a single bounding box is supported. Extensions may support additional areas. If multiple areas are provided, the union of the bounding boxes describes the spatial extent.
   */
  bbox?: Array<Array<number>>
  /**
   * Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude. In the Core this is the only supported coordinate reference system. Extensions may support additional coordinate reference systems and add additional enum values.
   */
  crs?: ExtentSpatialApiModel.CrsEnum
}
export namespace ExtentSpatialApiModel {
  export type CrsEnum = 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
  export const CrsEnum = {
    HttpWwwOpengisNetDefCrsOgc13Crs84:
      'http://www.opengis.net/def/crs/OGC/1.3/CRS84' as CrsEnum,
  }
}
