/**
 * Building Blocks specified in OGC API - Records - Part 1: Core
 * Common components used in the [OGC standard \"OGC API - Records - Part 1: Core\"] (https://docs.ogc.org/DRAFTS/20-004.html).  OGC API - Records - Part 1: Core 1.0 is an OGC Standard. Copyright (c) 2020 Open Geospatial Consortium. To obtain additional rights of use, visit https://www.ogc.org/legal/ .  This document is also available on [OGC](http://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/ogcapi-records-1.yaml).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pvretano@pvretano.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultilinestringGeoJSONApiModel } from './multilinestringGeoJSON.api.model'
import { PointGeoJSONApiModel } from './pointGeoJSON.api.model'
import { GeometrycollectionGeoJSONApiModel } from './geometrycollectionGeoJSON.api.model'
import { MultipointGeoJSONApiModel } from './multipointGeoJSON.api.model'
import { MultipolygonGeoJSONApiModel } from './multipolygonGeoJSON.api.model'
import { PolygonGeoJSONApiModel } from './polygonGeoJSON.api.model'
import { LinestringGeoJSONApiModel } from './linestringGeoJSON.api.model'

/**
 * @type GeometryGeoJSONApiModel
 * @export
 */
export type GeometryGeoJSONApiModel =
  | GeometrycollectionGeoJSONApiModel
  | LinestringGeoJSONApiModel
  | MultilinestringGeoJSONApiModel
  | MultipointGeoJSONApiModel
  | MultipolygonGeoJSONApiModel
  | PointGeoJSONApiModel
  | PolygonGeoJSONApiModel
